site_name: Gnosis Online
site_description: Gnosis Online lore and game documentation
site_url: https://lyon1255.github.io/gnosis-online-docs/

theme:
  name: material
  language: hu

  palette:
    scheme: slate
    primary: black
    accent: deep purple

  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables

  - toc:
      title: Tartalomjegyzék
      permalink: true
      permalink_title: Közvetlen hivatkozás erre a fejezetre
      toc_depth: 3

  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

copyright: "© 2026 Gnosis Online"

extra:
  generator: false
