site_name: Gnosis Online
site_description: Gnosis Online lore and game documentation
site_url: https://lyon1255.github.io/gnosis-online-docs/

theme:
  name: material
  language: hu

  palette:
    scheme: slate

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
