// Auto-generated by Embermask Forge Event Designer. Do not edit.

interface ForgeUnityObjectRef {
    readonly $unityType: string;
    readonly name: string;
    readonly instanceId: number;
}

interface ForgeEventMap {
    "TARGET_CHANGED": {
        unit: string;
        guid: string;
        exists: boolean;
    };
    "UNIT_HEALTH_CHANGED": {
        unit: string;
        guid: string;
        current: number;
        max: number;
    };
}

declare namespace Forge {
    namespace Events {
        function on<K extends keyof ForgeEventMap>(eventName: K, callback: (payload: ForgeEventMap[K]) => void): () => void;
        function off<K extends keyof ForgeEventMap>(eventName: K, callback: (payload: ForgeEventMap[K]) => void): void;
        function onUnit<K extends keyof ForgeEventMap>(eventName: K, unitToken: string, callback: (payload: ForgeEventMap[K]) => void): () => void;
    }
}
